# MySQL Configuration (Hibernate automatically detects Dialect for MySQL)
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=BRVLovZuYpLNbOHupmUIhERycYZnPqmN
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis Cache and Connection Configuration
spring.data.redis.host=redis.railway.internal
spring.data.redis.port=6379
#spring.data.redis.password=WFXQyubiDdGBohVTZBTguKXXZROnQCFT
spring.data.redis.time-to-live=300000

# SMTP E-Mail configuration for OTP dispatch
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rahulgss@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5005
spring.mail.properties.mail.smtp.writetimeout=5000

# JWT Cryptographic Credentials (HS512 needs a 64-byte key)
# Value must be adjusted with an environment secret injection or customized
deltaclause.jwt.secret=4f63c874df1cfdb1251e6008ab9dfa5db8fb64850d99ff68dddb2a4fb86ec16fc67f40cfd9d280ea970f031be0bd2ec7f7fe009d7dfae055da7c8d9e26fffeaa
deltaclause.jwt.expiration-ms=86400000

# Server Port config
server.port=8080
